# (c) 2026 Warren Usui
# This code is licensed under the MIT license (see LICENSE.txt
# for details)
"""
Linear programming verification of optiomal set covering solution
"""
# framework generated by Claude AI using the keywords:
# ai claude python code pulp set covering problem mimimum number
#
import json
import pulp

# 1. Data: Elements to cover and sets available

with open('data/team_pairs.json', 'r', encoding='utf-8') as efd:
    elements = list(json.load(efd))
#elements = ['e1', 'e2', 'e3', 'e4', 'e5']

with open('data/plyr_team_pair.json', 'r', encoding='utf-8') as ifd:
    sets = json.load(ifd)

#sets = {
#    'SetA': ['e1', 'e2', 'e3'],
#    'SetB': ['e2', 'e4'],
#    'SetC': ['e3', 'e4', 'e5'],
#    'SetD': ['e1', 'e5']
#}

# 2. Problem: Minimize the number of sets
prob = pulp.LpProblem("SetCovering", pulp.LpMinimize)

# 3. Decision Variables: Binary (1 if set is chosen, 0 otherwise)
set_vars = pulp.LpVariable.dicts("Set", sets.keys(), cat=pulp.LpBinary)

# 4. Objective Function: Minimize total sets
prob += pulp.lpSum([set_vars[i] for i in sets.keys()])

# 5. Constraints: Each element must be covered at least once
for element in elements:
    prob += pulp.lpSum([set_vars[i] for i in sets.keys()
                       if element in sets[i]]) >= 1

# 6. Solve the problem
prob.solve()

# 7. Print Results
print(f"Status: {pulp.LpStatus[prob.status]}")
print("Selected Sets:")
for v in prob.variables():
    if v.varValue > 0:
        print(v.name)
print(f"Minimum Sets Needed: {pulp.value(prob.objective)}")
