# (c) 2026 Warren Usui
# This code is licensed under the MIT license (see LICENSE.txt
# for details)
"""
Analyze groups in temp_solution for 18 player solutions
"""
import json
from itertools import chain

def brain_check(indiv, verbose=False):
    """
    Loop through groups of players generated by brainz and extract log
    information about the most likely soulutions found.  Produce two types
    of solutions, 19 player solutions where a player can be removed because
    it links to zero singly found team pairs, or a 19 player solution where
    two players linked two separate but singular two team pairs can be replaced
    by any other player that has played for all four of those teams.
    """
    with open('data/plyr_team_pair.json', 'r', encoding='utf-8') as ifd:
        full_data = json.load(ifd)
    with open('data/temp_solution.json', 'r', encoding='utf-8') as ifd:
        solutions = json.load(ifd)
    with open('data/team_pairs.json', 'r', encoding='utf-8') as ifd:
        tpairs = json.load(ifd)
    s18_list = []
    ecount = []
    local_log = f'* {indiv}\n'
    for solution in solutions:
        table = dict(list(map(lambda a: [a, []], tpairs.keys())))
        for player in solution:
            for pairing in full_data[player]:
                table[pairing].append(player)
        singletons = dict(list(map(lambda a: [a, []], solution)))
        for entry in table:
            if len(table[entry]) == 1:
                singletons[table[entry][0]].append(entry)
        if verbose:
            for keyv in singletons:
                print(keyv, singletons[keyv])
        scount = []
        ecount = []
        for fields in singletons:
            if len(singletons[fields]) == 0:
                if verbose:
                    print('empty player found')
                ecount.append(fields)
            if len(singletons[fields]) == 1:
                scount.append([fields, singletons[fields]])
        if len(ecount) > 0:
            odata = list(filter(lambda a: a not in ecount, solution))
            s18_list.append('|'.join(odata))
            local_log += '|'.join(odata) + '\n'
        if len(scount) > 1:
            if verbose:
                print(scount)
            for dentry in scount:
                solution.remove(dentry[0])
            xlist = list(map(lambda a: full_data[a], solution))
            xxlist = list(chain.from_iterable(xlist))
            xxxlist = list(set(xxlist))
            if verbose:
                print(len(xxxlist))
            if len(xxxlist) >= 433:
                if verbose:
                    print('possible fixable list found')
                local_log += '/'.join(solution) + ':' + '/'.join(
                            [scount[0][0], scount[0][1][0],
                             scount[1][0], scount[1][1][0]]) +'\n'
    with open(f"logs/{indiv}.log", 'w', encoding='utf-8') as lfile:
        lfile.write(local_log)

if __name__ == "__main__":
    brain_check('hawkila01')
